### ISSUE TITLE
Legacy windowing system

### ISSUE THREAD

**Issue by mikolajlubiak** [flathub/net.mullvad.MullvadBrowser#24]
GNOME Software says that Mullvad Browser is potentially unsafe, because it uses legacy windowing system (X11 instead of Wayland).
Could you please compile it for Wayland/make it use Wayland?
Thanks.

**Comment by Erick555** [comment]
App supports [wayland](https://github.com/flathub/net.mullvad.MullvadBrowser/blob/master/net.mullvad.MullvadBrowser.yml#L22) but you need to enable it yourself (same as you do for firefox).

**Comment by mikolajlubiak** [comment]
Why doesn't it show this warning on the Librewolf's Flatpak though?

**Comment by Erick555** [comment]
Perhaps Librewolf uses some patches on firefox to force using wayland, I don't know for sure

**Comment by mikolajlubiak** [comment]
Okey, thank you for the response. I decided to install Librewolf, but I still think that Mullvad Browser is an amazing browser. ❤️
It would be nice if you considered making Mullvad Browser use Wayland by default.

**Comment by Erick555** [comment]
Yo can do it yourself by running `flatpak --user override --nosocket=x11 --socket=fallback-x11 net.mullvad.MullvadBrowser`. It should achieve what Librewofl does.

**Comment by mikolajlubiak** [comment]
Thanks, a lot. I will definitely try it. It would be nice if it would be done by default though.

**Comment by mikolajlubiak** [comment]
This suggests that soon Wayland might be the default option: https://www.phoronix.com/news/Firefox-Wayland-Possibly-Soon
Anyway, thanks for help.
