### ISSUE TITLE
Browser closes after start with "Your profile 'MullvadBrowser' could not be loaded".

### ISSUE THREAD

**Issue by Zeabyte** [flathub/net.mullvad.MullvadBrowser#46]
Suddenly today I cannot start the flatpak anymore. After start a popup appears with the text: "Profile not found" - "Your profile "MullvadBrowser" cannot be loaded. It may not exist or may not be accessible.".

`flatpak run` with `-v` prints the following: (translated from another language)
```
mkdir: the directory ".config/ibus" cannot be created: The file system is read-only
ln: the symbolic link '.config/ibus' could not be created: The file system is read-only
cp: the call to stat for 'start-mullvad-browser.desktop' is not possible: file or directory not found
sed: ../start-mullvad-browser.desktop cannot be read: file or directory not found
sed: ../start-mullvad-browser.desktop cannot be read: file or directory not found
sed: start-mullvad-browser.desktop cannot be read: file or directory not found
sed: ../start-mullvad-browser.desktop cannot be read: file or directory not found
mkdir: the directory "/app/lib/mullvad-browser/.local/" cannot be created: The file system is read-only
ln: the symbolic link '/app/lib/mullvad-browser/.local//share' could not be created: file or directory not found
```

My system: Fedora 40 with KDE

**Comment by Zeabyte** [comment]
There seem to be no new updates available. Here is the output of `flatpak info` (translated):

```
Mullvad Browser - Free the internet from mass surveillance

Identifier: net.mullvad.MullvadBrowser
Ref: app/net.mullvad.MullvadBrowser/x86_64/stable
Architecture: x86_64
Branch: stable
Version: 13.5
License: MPL-2.0
Source: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 258.7 MB
Runtime: org.freedesktop.Platform/x86_64/23.08
Sdk: org.freedesktop.Sdk/x86_64/23.08
Commit: 50668bcc21810c2977c107f2a602431571781b3b1fbe5be3931eddeb16c774a4
Parent: 8a3323b489d6357d783216dbfc40ebbb5706c211423d8ff7d5610fa61d847cb2
Subject: remove unnecessary patches/mullvad-browser/remove-register-app-start-mullvad-browser.patch (d9aba6e6)
Date: 2024-06-19 15:55:15 +0000
```

**Comment by mofongox** [comment]
> It's unfortunate that although a fix [was pushed 17 hours ago](https://github.com/flathub/net.mullvad.MullvadBrowser/commit/7e9c7cc7b8afca8205bffc5100ee737c5aab6327), it has not been deployed.
> 
> You can try the fixed version: [#44 (comment)](https://github.com/flathub/net.mullvad.MullvadBrowser/pull/44#issuecomment-2179072669)

The test version suggested in that comment is working.

```
Mullvad Browser - Free the internet from mass surveillance

ID: net.mullvad.MullvadBrowser
Ref: app/net.mullvad.MullvadBrowser/x86_64/test
Arch: x86_64
Branch: test
Version: 13.5
License: MPL-2.0
Origin: mullvadbrowser-origin
Collection: org.flathub.Test.Build112221
Installation: user
Installed: 258.7 MB
Runtime: org.freedesktop.Platform/x86_64/23.08
Sdk: org.freedesktop.Sdk/x86_64/23.08
Commit: 64ef3609f077f7563ee0e7d73fb1194ca9cf801fdc32dec2d4ac30ad6b887e22
Subject: fix: profiles are not persisted (b36c5515)
Date: 2024-06-19 16:17:24 +0000
```

**Comment by mattmilano** [comment]
New version works, but it appears that the previous version deleted the profile. Have to completely redo all settings. :\

**Comment by mattmilano** [comment]
> > Since upstream changed where Mullvad stores its profile, how does that impact the Flatpak version? Is it still stored in .var/app folder that Flatpaks normally use?
> 
> It's still under `.var/app`. But inside that directory, it stores the data in `.mullvad-browser/.mullvad/mullvadbrowser` instead of `.mullvad/mullvadbrowser`

Cool. Thanks for your hard work on this!

**Comment by Zeabyte** [comment]
Everything is working perfectly now! Thank you so much for your work @proletarius101
