### ISSUE TITLE
Can't play H264 videos with 24.08 SDK

### ISSUE THREAD

**Issue by proletarius101** [flathub/net.mullvad.MullvadBrowser#54]
https://github.com/mullvad/mullvad-browser/issues/337

> For some reason, my Mullvad browser doesn't want to play H264 videos anymore.
> It started yesterday and I have no idea why...
> OS: Ubuntu 24.04
> 
> Here are 2 examples of videos not playing:
> https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/avc-mp3-sita.mov
> https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/avc-aac-big-buck-bunny.m4v
> 
> Other formats seem to be playing just fine based on my tests.
> https://tools.woolyss.com/html5-audio-video-tester/
> 
> Anyone is experiencing the same issue ?
> Any solution that you know of ?
> 
> Thx

**Comment by Erick555** [comment]
you need to install org.freedesktop.Platform.ffmpeg-full//24.08. Perhaps this can be made autodownloaded here

**Comment by Erick555** [comment]
you're right. one possibility is firefox esr 115 which mullvad is based on isn't compatible with ffmpeg 7.
